CREATE TABLE EMPLOYEES
(
    EMPLOYEE_NUMBER INT NOT NULL,
    LAST_NAME CHAR(50) NOT NULL,
    FIRST_NAME CHAR(50) NOT NULL,
    SALARY INT,
    DEPT_ID INT,
    CONSTRAINT EMPLOYES_PK PRIMARY KEY(EMPLOYEE_NUMBER)
);
