INSERT INTO EMPLOYEES(EMPLOYEE_NUMBER,LAST_NAME,FIRST_NAME,SALARY,DEPT_ID)
VALUES(1001,'SMITH','JHON',6200,500);

INSERT INTO EMPLOYEES(EMPLOYEE_NUMBER,LAST_NAME,FIRST_NAME,SALARY,DEPT_ID)
VALUES(1002,'ROMAN','RINGS',9200,600);

INSERT INTO EMPLOYEES(EMPLOYEE_NUMBER,LAST_NAME,FIRST_NAME,SALARY,DEPT_ID)
VALUES(1003,'ANDREW','RUSSEL',5200,500);


INSERT INTO EMPLOYEES(EMPLOYEE_NUMBER,LAST_NAME,FIRST_NAME,SALARY,DEPT_ID)
VALUES(1004,'LORD','SHANTO',4200,600);

INSERT INTO EMPLOYEES(EMPLOYEE_NUMBER,LAST_NAME,FIRST_NAME,SALARY,DEPT_ID)
VALUES(1005,'DAA','PAPON',3200,700);

INSERT INTO EMPLOYEES(EMPLOYEE_NUMBER,LAST_NAME,FIRST_NAME,SALARY,DEPT_ID)
VALUES(1006,'TIKTOK STAR','SABBIR',1000,700);

INSERT INTO EMPLOYEES(EMPLOYEE_NUMBER,LAST_NAME,FIRST_NAME,SALARY,DEPT_ID)
VALUES(1007,'360','SHOHAN',3213,500);